### ISSUE TITLE
missing the paper url in readme.md 

### ISSUE THREAD

**Issue by 0x1orz** [mit-ll/AlphaSeq_Antibody_Dataset#2]
the text “Additional information describing how this data was generated can be found [link to paper]” is not atteched the url

**Comment by smiles724** [comment]
I am also curious about the description in the original paper. Can the author provide more details and complement the missing link?

**Comment by 0x1orz** [comment]
@smiles724  this paper may be needed for you ?  https://www.nature.com/articles/s41597-022-01779-4#article-info
